#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
umask 077
REPOSITORY_DIRECTORY=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
ENV_FILE=/etc/daily-cd/setup.env

banner "Daily CD installation on homelab"

stage "Confirm the execution target"
say "Run this wizard on homelab, from a reviewed Daily checkout."
say "Stages: host check, local API credential, installation/check, timer activation."
[[ $(id -u) == 0 ]] || { warn "Run with sudo bash scripts/setup-daily-cd.sh"; exit 1; }
[[ $(hostname -s) == homelab ]] || { warn "This is not the expected homelab host."; exit 1; }
for executable in docker python3 systemctl install; do
  command -v "$executable" >/dev/null || { warn "Missing $executable"; exit 1; }
done
if systemctl is-active --quiet daily-cd.service || systemctl is-active --quiet daily-cd.timer; then
  warn "Existing CD is active. Stop its timer and wait for the service to finish before updating."
  exit 1
fi
confirm "Proceed with these four setup stages on homelab?" || exit 0

stage "Create a Coolify API token"
open_url "http://100.118.76.98:8000/settings"
step "Enable API access in Coolify Settings if it is disabled."
open_url "http://100.118.76.98:8000/security/api-tokens"
step "Keys & Tokens > API tokens: create daily-cd in the team that owns Daily."
step "Select read, write, and deploy. Do not select root or sensitive permissions."
say "The token stays in root-only files under /etc/daily-cd; it is not sent to GitHub."
install -d -m 0700 /etc/daily-cd
ask_secret COOLIFY_TOKEN "Paste the token (hidden):"
[[ -n "$COOLIFY_TOKEN" ]] || { warn "Token cannot be empty."; exit 1; }
write_env COOLIFY_TOKEN "$COOLIFY_TOKEN"
printf '%s\n' "$COOLIFY_TOKEN" > /etc/daily-cd/token
chmod 0600 /etc/daily-cd/token /etc/daily-cd/setup.env
unset COOLIFY_TOKEN

stage "Install files and run a read-only preflight"
install -d -m 0755 /usr/local/lib/daily-cd
install -d -m 0700 /var/lib/daily-cd
install -m 0755 "$REPOSITORY_DIRECTORY/scripts/coolify_cd.py" /usr/local/lib/daily-cd/coolify_cd.py
if [[ ! -f /etc/daily-cd/config.json ]]; then
  install -m 0600 "$REPOSITORY_DIRECTORY/deploy/coolify/cd-config.example.json" /etc/daily-cd/config.json
fi
install -m 0644 "$REPOSITORY_DIRECTORY/deploy/coolify/daily-cd.service" /etc/systemd/system/daily-cd.service
install -m 0644 "$REPOSITORY_DIRECTORY/deploy/coolify/daily-cd.timer" /etc/systemd/system/daily-cd.timer
systemctl daemon-reload
python3 /usr/local/lib/daily-cd/coolify_cd.py --check
say "Preflight passed. No application deployment has been started."
say "GHCR must permit this host to pull ghcr.io/poppyseedcake/daily:cd."
say "If the package is private, configure root's Docker registry login separately."
pause "Press Enter after confirming registry access and the publishing workflow is merged."

stage "Enable automatic releases"
say "Every five minutes the host will pull the tested cd channel and deploy a changed image."
say "Each release stops Daily briefly for backup, migration, and startup."
say "Do not manually deploy, edit tasks, or run database commands during CD."
say "A failure leaves a maintenance journal and blocks automatic retries."
if confirm "Restore previously enabled mail tasks automatically after health and configuration checks?"; then
  install -d -m 0755 /etc/systemd/system/daily-cd.service.d
  printf '[Service]\nExecStart=\nExecStart=/usr/bin/python3 /usr/local/lib/daily-cd/coolify_cd.py --resume-delivery\n' \
    > /etc/systemd/system/daily-cd.service.d/delivery.conf
else
  if [[ -f /etc/systemd/system/daily-cd.service.d/delivery.conf ]]; then
    warn "An existing resume-delivery override remains. Review it before activation."
    exit 1
  fi
  say "Mail tasks will stay disabled after each release until you accept it in Coolify."
fi
systemctl daemon-reload
if confirm "Enable the timer now? A new cd image can immediately cause a deployment."; then
  systemctl enable --now daily-cd.timer
  say "Timer enabled. Check: sudo journalctl -u daily-cd.service -n 80 --no-pager"
else
  say "Installed but not enabled. Later run: sudo systemctl enable --now daily-cd.timer"
fi
finish
